### ISSUE TITLE
a cheater is in your benchmark ;)

### ISSUE THREAD

**Issue by gero3** [stepheneb/webgl-matrix-benchmarks#1]
canvasMatrix4 doesn't get random numbers.

just see the console in 
http://gero3.github.com/webgl-matrix-benchmarks/matrix_benchmark.html

To see the diff with your repo
https://github.com/gero3/webgl-matrix-benchmarks/commit/5cf55584fc511f62240abbc3cb62e302175ac87b

**Comment by stepheneb** [comment]
Hi Gero,

Sorry I didn't respond earlier (did github send me an email ...?) -- anyway I'm confused now. I don't use CanvasMatrix but it looks like creating a new CanvasMatrix4() doesn't accept an array for setting the initial values ... seems strange. Did you notice any way around that issue?

**Comment by gero3** [comment]
```
function canvasMatrixRandom() {
    var a =  new CanvasMatrix4();
    a.load([
      Math.random()*100, Math.random()*100, Math.random()*100, Math.random()*100,
      Math.random()*100, Math.random()*100, Math.random()*100, Math.random()*100,
      Math.random()*100, Math.random()*100, Math.random()*100, Math.random()*100,
      Math.random()*100, Math.random()*100, Math.random()*100, Math.random()*100
    ]);
    console.log(a);
    return a; 
};
```

this should work
